QUESTIONS = [
    {"id": "q1", "question": "You have a free day in your dental practice. Do you spend it hosting a community outreach event or researching innovative dental materials?", "answers": {"E": "Hosting community event", "I": "Researching materials"}},
    {"id": "q2", "question": "When explaining a treatment plan, do you prefer using clear step-by-step instructions or inspiring patients with the bigger picture?", "answers": {"S": "Step-by-step instructions", "N": "Bigger picture"}},
    {"id": "q3", "question": "A colleague suggests an unconventional treatment method. Do you evaluate it based on clinical evidence or consider how it might improve patient comfort?", "answers": {"T": "Clinical evidence", "F": "Patient comfort"}},
    {"id": "q4", "question": "Would you rather work in a high-tech structured dental clinic or travel as a consultant for various practices?", "answers": {"J": "Structured clinic", "P": "Traveling consultant"}},
    {"id": "q5", "question": "Do you enjoy mentoring young dentists in hands-on training or brainstorming futuristic dental AI applications?", "answers": {"E": "Mentoring hands-on", "I": "Brainstorming AI"}},
    {"id": "q6", "question": "When confronted with a new dental trend, do you prefer testing it on real cases immediately or analyzing extensive research before deciding?", "answers": {"S": "Test on real cases", "N": "Analyze research first"}},
    {"id": "q7", "question": "In a case of dental malpractice, do you focus on legal facts and protocols or empathize with the patient’s experience?", "answers": {"T": "Legal facts", "F": "Patient experience"}},
    {"id": "q8", "question": "Would you rather have a well-defined career trajectory in dentistry or constantly explore new roles and challenges?", "answers": {"J": "Well-defined", "P": "Explore new roles"}},
    {"id": "q9", "question": "Do you thrive in large networking events with other healthcare professionals or prefer deep one-on-one discussions?", "answers": {"E": "Large networking events", "I": "One-on-one discussions"}},
    {"id": "q10", "question": "A new treatment is gaining popularity. Do you rely on long-term clinical studies or try it out based on promising preliminary results?", "answers": {"S": "Long-term studies", "N": "Preliminary results"}},
    {"id": "q11", "question": "Would you rather make dental career choices based on pure logical demand or personal passion and purpose?", "answers": {"T": "Logical demand", "F": "Passion and purpose"}},
    {"id": "q12", "question": "Your work schedule: Do you prefer fixed hours with set patient appointments or a flexible schedule allowing spontaneous opportunities?", "answers": {"J": "Fixed hours", "P": "Flexible schedule"}},
    {"id": "q13", "question": "Would you rather present groundbreaking research at an international conference or work quietly on developing a revolutionary dental tool?", "answers": {"E": "Present research", "I": "Develop dental tool"}},
    {"id": "q14", "question": "Do you enjoy working with concrete clinical data or envisioning futuristic changes in dental technology?", "answers": {"S": "Concrete data", "N": "Futuristic vision"}},
    {"id": "q15", "question": "When making a dental business decision, do you prioritize cost-effectiveness or the emotional impact on patients?", "answers": {"T": "Cost-effectiveness", "F": "Emotional impact"}},
    {"id": "q16", "question": "Do you enjoy creating detailed treatment workflows or adapting dynamically to patient needs?", "answers": {"J": "Detailed workflows", "P": "Adapt dynamically"}},
    {"id": "q17", "question": "Do you prefer discussing evolving dental trends with colleagues or independently researching emerging technologies?", "answers": {"E": "Discuss trends", "I": "Research alone"}},
    {"id": "q18", "question": "Do you trust standardized dental procedures or prefer experimenting with newer treatment methods?", "answers": {"S": "Standardized procedures", "N": "Experimenting"}},
    {"id": "q19", "question": "When analyzing a difficult case, do you trust scientific data more or the patient’s personal experience?", "answers": {"T": "Scientific data", "F": "Patient’s experience"}},
    {"id": "q20", "question": "Would you rather have a stable, predictable dental career or a dynamic one with constant changes and new projects?", "answers": {"J": "Stable career", "P": "Dynamic career"}}
]

CAREERS = {
    "ESTJ": ["Dental Practice Manager", "Regulatory Affairs Specialist", "Public Health Dentist", "Academic Program Director", "Dental Insurance Consultant"],
    "ESFJ": ["Patient Care Coordinator", "Community Dental Coordinator", "Healthcare Marketing Specialist", "Oral Health Educator", "Dental Sales Representative"],
    "ENTJ": ["Dental Business Consultant", "Strategic Healthcare Advisor", "Dental Hospital Administrator", "Clinical Research Manager", "Dental AI Entrepreneur"],
    "ENFJ": ["Dental Educator", "Public Health Advocate", "Wellness Program Director", "Healthcare Recruiter", "Non-Profit Dental Organizer"],
    "ISTJ": ["Compliance Officer", "Dental Records Manager", "Healthcare Auditor", "Insurance Claims Analyst", "Dental Regulatory Officer"],
    "ISFJ": ["Dental HR Manager", "Medical Billing Specialist", "Quality Assurance Officer", "Dental NGO Coordinator", "Insurance Underwriter"],
    "INTJ": ["Dental Innovation Consultant", "Healthcare Data Analyst", "Dental Biotech Researcher", "Forensic Odontologist", "Patent Analyst"],
    "INFJ": ["Dental Ethics Consultant", "Health Communication Specialist", "Public Policy Advisor", "Holistic Dentistry Advocate", "Medical Writer"],
    "ESTP": ["Dental Equipment Sales Representative", "Healthcare Event Organizer", "Dental Tech Startup Founder", "Medical Tourism Consultant", "Dental Product Marketing Specialist"],
    "ESFP": ["Social Media Influencer (Dentistry)", "Dental Public Speaker", "Corporate Wellness Coach", "Dental PR Specialist", "Event Manager for Dental Conferences"],
    "ENTP": ["Dental Innovation Strategist", "Healthcare Tech Entrepreneur", "Medical AI Consultant", "Dental App Developer", "Dental Content Creator"],
    "ENFP": ["Health and Wellness Coach", "Dental Outreach Coordinator", "Career Coach for Dentists", "Dental Startup Consultant", "Patient Experience Specialist"],
    "ISTP": ["Forensic Odontologist", "Dental CAD/CAM Designer", "Dental 3D Printing Specialist", "Medical Device Tester", "Dental Materials Researcher"],
    "ISFP": ["Dental Illustrator", "Healthcare Graphic Designer", "Dental Photography Specialist", "Dental Art Therapist", "Creative Content Developer (Healthcare)"],
    "INTP": ["Dental Research Scientist", "Pharmaceutical Industry Consultant", "Artificial Intelligence in Dentistry Researcher", "Bioinformatics Specialist", "Dental Tech Innovator"],
    "INFP": ["Holistic Dentistry Advocate", "Ethics Consultant in Healthcare", "Wellness Blogger (Dentistry)", "Mental Health and Dental Wellness Consultant", "Non-Profit Health Organization Manager"]
}
